<?php

namespace OC\Metadata;

use OCP\AppFramework\Db\Entity;
use JsonSerializable;

/**
 * @method int getFileId()
 * @method void setFileId(int $fileId)
 * @method string getGroupName()
 * @method void setGroupName(string $groupName)
 */
class FileMetadata extends Entity implements JsonSerializable {
	protected int $fileId;
	protected string $groupName;
	protected string $data;
	private array $metadata;

	public function __construct() {
		$this->addType('fileId', 'integer');
		$this->addType('groupName', 'string');
		$this->addType('data', 'string');
	}

	#[\ReturnTypeWillChange]
	public function jsonSerialize() {
		return [
			'file_id' => $this->fileId,
			'group_name' => $this->groupName,
			'data' => json_encode($this->data),
		];
	}

	public function propertyToColumn($property) {
		// Make sure that getId returns the fileid of the metadata
		if ($property === 'id') {
			return 'fileid';
		} else {
			return parent::propertyToColumn($property);
		}
	}

	public function getMetadata(): array {
		return $this->metadata;
	}

	public function setMetadata(array $data): void {
		$this->metadata = $data;
		$this->setter('data', [json_encode($data), $data]);
	}

	protected function setter($name, $args) {
		if ($name === 'data') {
			$this->metadata = $args[1] ?? json_decode($args[0]);
		}
		parent::setter($name, $args); // TODO: Change the autogenerated stub
	}
}
