<?php declare(strict_types=1);
/**
 * @copyright Copyright (c) 2016, ownCloud, Inc.
 *
 * @author Christoph Wurst <christoph@winzerhof-wurst.at>
 * @author Joas Schilling <coding@schilljs.com>
 * @author Morris Jobke <hey@morrisjobke.de>
 * @author Robin Appelman <robin@icewind.nl>
 * @author Roeland Jago Douma <roeland@famdouma.nl>
 * @author Thomas Müller <thomas.mueller@tmit.eu>
 *
 * @license AGPL-3.0
 *
 * This code is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License, version 3,
 * as published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License, version 3,
 * along with this program. If not, see <http://www.gnu.org/licenses/>
 *
 */

namespace OC\Metadata;

use OCP\AppFramework\Db\Entity;
use JsonSerializable;

/**
 * @method string getGroupName()
 * @method void setGroupName(string $groupName)
 */
class FileMetadata extends Entity {
	protected ?string $groupName = null;
	protected ?string $data = null;
	private ?array $metadata = null;

	public function __construct() {
		$this->addType('groupName', 'string');
		$this->addType('data', 'string');
	}

	public function getMetadata(): array {
		return $this->metadata;
	}

	public function setMetadata(array $data): void {
		$this->setter('data', [json_encode($data), $data]);
	}

	protected function setter($name, $args) {
		if ($name === 'data') {
			$this->metadata = $args[1] ?? json_decode($args[0], true);
		}
		parent::setter($name, $args); // TODO: Change the autogenerated stub
	}
}
