<?php

namespace OC\Metadata;

use OCP\AppFramework\Db\Entity;
use JsonSerializable;

/**
 * @method string getGroupName()
 * @method void setGroupName(string $groupName)
 */
class FileMetadata extends Entity {
	protected ?string $groupName = null;
	protected ?string $data = null;
	private ?array $metadata = null;

	public function __construct() {
		$this->addType('groupName', 'string');
		$this->addType('data', 'string');
	}

	public function getMetadata(): array {
		return $this->metadata;
	}

	public function setMetadata(array $data): void {
		$this->metadata = $data;
		$this->setter('data', [json_encode($data), $data]);
	}

	protected function setter($name, $args) {
		if ($name === 'data') {
			$this->metadata = $args[1] ?? json_decode($args[0]);
		}
		parent::setter($name, $args); // TODO: Change the autogenerated stub
	}
}
